# global configuration
global:
   scrape_interval: 15s
   evaluation_interval: 15s

rule_files:

scrape_configs:
   - job_name: 'prometheus'
     static_configs:
     - targets: ['127.0.0.1:9090']

   - job_name: 'reservation-business-services'
     metrics_path: '/actuator/prometheus'
     scrape_interval: 5s
     static_configs:
     - targets: ['reservation-business-services-docker:8500']

   - job_name: 'reservation-services'
     metrics_path: '/actuator/prometheus'
     scrape_interval: 5s
     static_configs:
     - targets: ['reservation-services-docker:8103']

   - job_name: 'room_services'
     metrics_path: '/actuator/prometheus'
     scrape_interval: 5s
     static_configs:
     - targets: ['room-services-docker:8101']

   - job_name: 'guest_services'
     metrics_path: '/actuator/prometheus'
     scrape_interval: 5s
     static_configs:
     - targets: ['guest-services-docker:8102']
